name: consistency-lab

# Important: A direct "git clone + docker compose up" will not work,
# Clients outside Docker need "127.0.0.1 mongo1 mongo2 mongo3" in their hosts file
# (Windows: C:\Windows\System32\drivers\etc\hosts, Linux/WSL: /etc/hosts).

x-mongo: &mongo
  image: mongo:8.3.11 # Latest version on September 2026
  restart: unless-stopped # auto-recover after crash/reboot, but respect manual stops

services:
  mongo1:
    <<: *mongo
    container_name: mongo1
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "${MONGO1_PORT:-27017}"]
    ports: ["${MONGO1_PORT:-27017}:${MONGO1_PORT:-27017}"]
    volumes: ["mongo1-data:/data/db"]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "${MONGO1_PORT:-27017}", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mongo2:
    <<: *mongo
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "${MONGO2_PORT:-27018}"]
    ports: ["${MONGO2_PORT:-27018}:${MONGO2_PORT:-27018}"]
    volumes: ["mongo2-data:/data/db"]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "${MONGO2_PORT:-27018}", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mongo3:
    <<: *mongo
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "${MONGO3_PORT:-27019}"]
    ports: ["${MONGO3_PORT:-27019}:${MONGO3_PORT:-27019}"]
    volumes: ["mongo3-data:/data/db"]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "${MONGO3_PORT:-27019}", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # One-shot job: init the replica set with the 3 nodes
  mongo-init:
    <<: *mongo
    container_name: mongo-init
    restart: "no"
    depends_on:
      mongo1: { condition: service_healthy }
      mongo2: { condition: service_healthy }
      mongo3: { condition: service_healthy }
    entrypoint:
      - mongosh
      - --host
      - mongo1:${MONGO1_PORT:-27017}
      - --quiet
      - --eval
      - |
        try {
          rs.status();
          print("Replica set already initiated");
        } catch (e) {
          printjson(rs.initiate({
            _id: "rs0",
            members: [
              { _id: 0, host: "mongo1:${MONGO1_PORT:-27017}", priority: 2 },
              { _id: 1, host: "mongo2:${MONGO2_PORT:-27018}", priority: 1 },
              { _id: 2, host: "mongo3:${MONGO3_PORT:-27019}", priority: 1 }
            ]
          }));
        }

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data: